package tn.esprit.examen.nomPrenomClasseExamen.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;
import java.util.Set;

@Entity
@AllArgsConstructor
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Equipement {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idEquipement;

    private String nomEquipement;

    // Backend-generated internal ANAPCO equipment reference (e.g. TN-PLANT-2-EQ-001).
    // Generated by EquipementService on create from the owning Site's codeRef; immutable on
    // update; never supplied by the client.
    @Schema(accessMode = Schema.AccessMode.READ_ONLY,
            description = "Backend-generated internal equipment reference (e.g. TN-PLANT-2-EQ-001). "
                    + "Read-only; ignored on create/update requests.")
    private String refEquipement;

    @Enumerated(EnumType.STRING)
    private StatusEquipement statusEquipement;

    // Real physical / manufacturer serial number: client-entered, optional, never fabricated.
    private String serialNumber;

    @ManyToOne
    @JsonIgnoreProperties("equipements")
    @JoinColumn(name = "categorie_id")
    private CategorieEquipement categorie;  // lien vers catégorie


    @ManyToOne
    @JoinColumn(name = "site_id")
    @JsonIgnoreProperties({"lincident", "equipements", "budgets", "manualExpenses"})
    private Sites site;

    @OneToMany(mappedBy = "equipement", cascade = CascadeType.ALL)
    @JsonIgnore
    private Set<Maintenance> maintenances;
}
