package tn.esprit.examen.nomPrenomClasseExamen.entities;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;
import tn.esprit.examen.nomPrenomClasseExamen.weather.entities.SiteType;

import java.util.Set;

@Entity
@AllArgsConstructor
@Getter
@Setter
@ToString
@NoArgsConstructor
public class Sites {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long idSite;

    // Backend-generated stable business identifier (ex: TN-PLANT-1, UK-PLANT-1).
    // Generated by SiteService on create; immutable through update; never supplied by the client.
    @Schema(accessMode = Schema.AccessMode.READ_ONLY,
            description = "Backend-generated stable business identifier (e.g. TN-PLANT-1). Read-only; ignored on create/update requests.")
    private String codeRef;
    private String nom;
    private Double latitude;
    private Double longitude;
    private String countryCode;
    private String currencyCode;
    @Enumerated(EnumType.STRING)
    private StatusSites statusSites;

    @Enumerated(EnumType.STRING)
    private SiteType siteType;

    // Cascade limited to PERSIST/MERGE: deleting a Site must never destroy its
    // operational or financial history (see SiteService delete guard, STEP 2A).
    @OneToMany(mappedBy = "sites", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    private Set<Incident> lincident;

    @OneToMany(mappedBy = "site", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    private Set<Equipement> equipements;

    @OneToMany(mappedBy = "site", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    private Set<BudgetMonthly> budgets;

    @OneToMany(mappedBy = "site", cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    private Set<ManualExpense> manualExpenses;

/*
👉 À l’écran, ton OPS peut filtrer :

            “Montre-moi tous les incidents sur les Pipelines du site UK-PLANT-1”.
*/

}
